project:
  type: website
  output-dir: docs

website:
  title: "Cyprus Events Guide"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: tab1.qmd
        text: About us
    logo: images/logo_tepak.png

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



